"""
report.py — Daemon task run report (migrated from nightcycle).

Captures the output of a daemon task run: which tasks ran, what they
produced, timing, errors, and any proposals requiring DA review.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass
class Proposal:
    """A single actionable proposal generated by a night-cycle task.

    For cross-domain proposals, ``required_approvers`` lists the domain_ids
    that must independently approve before ``status`` can become "approved".
    The ``approvals`` dict tracks per-domain decisions.  A proposal is
    rejected if *any* required approver rejects.
    """

    proposal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    task: str = ""
    domain_id: str = ""
    proposal_type: str = ""          # e.g. "glossary_add", "glossary_prune", "cross_domain_similarity"
    summary: str = ""
    detail: dict[str, Any] = field(default_factory=dict)
    status: str = "pending"          # pending | approved | rejected

    # Dual-approval fields for cross-domain proposals
    required_approvers: list[str] = field(default_factory=list)
    approvals: dict[str, str] = field(default_factory=dict)  # {domain_id: "approved"|"rejected"}

    def resolve_approval(self, domain_id: str, decision: str) -> str:
        """Record one approver's decision and recompute overall status.

        Parameters
        ----------
        domain_id : str
            The domain whose authority is approving/rejecting.
        decision : str
            Either ``"approved"`` or ``"rejected"``.

        Returns
        -------
        str
            The new overall ``status`` after this decision.
        """
        if decision not in ("approved", "rejected"):
            raise ValueError(f"decision must be 'approved' or 'rejected', got {decision!r}")
        self.approvals[domain_id] = decision

        # Any rejection → overall rejected
        if decision == "rejected":
            self.status = "rejected"
            return self.status

        # Check if all required approvers have approved
        if self.required_approvers:
            all_approved = all(
                self.approvals.get(did) == "approved"
                for did in self.required_approvers
            )
            self.status = "approved" if all_approved else "pending"
        else:
            # No required_approvers → legacy single-approval path
            self.status = decision
        return self.status

    def to_dict(self) -> dict[str, Any]:
        result: dict[str, Any] = {
            "proposal_id": self.proposal_id,
            "task": self.task,
            "domain_id": self.domain_id,
            "proposal_type": self.proposal_type,
            "summary": self.summary,
            "detail": self.detail,
            "status": self.status,
        }
        if self.required_approvers:
            result["required_approvers"] = self.required_approvers
            result["approvals"] = self.approvals
        return result


@dataclass
class TaskResult:
    """Result of a single night-cycle task execution."""

    task: str = ""
    domain_id: str = ""
    success: bool = True
    duration_seconds: float = 0.0
    error: str | None = None
    proposals: list[Proposal] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "task": self.task,
            "domain_id": self.domain_id,
            "success": self.success,
            "duration_seconds": self.duration_seconds,
            "error": self.error,
            "proposals": [p.to_dict() for p in self.proposals],
            "metadata": self.metadata,
        }


@dataclass
class NightCycleReport:
    """Aggregate report for a complete night cycle run."""

    run_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    started_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    finished_at: str | None = None
    triggered_by: str = "scheduler"   # "scheduler" | actor_id
    status: str = "running"           # running | completed | failed | cancelled
    task_results: list[TaskResult] = field(default_factory=list)
    total_proposals: int = 0

    def finish(self) -> None:
        self.finished_at = datetime.now(timezone.utc).isoformat()
        self.status = "completed" if all(r.success for r in self.task_results) else "failed"
        self.total_proposals = sum(len(r.proposals) for r in self.task_results)

    def to_dict(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "started_at": self.started_at,
            "finished_at": self.finished_at,
            "triggered_by": self.triggered_by,
            "status": self.status,
            "task_results": [r.to_dict() for r in self.task_results],
            "total_proposals": self.total_proposals,
        }
